### ISSUE TITLE
Colab TPU sample not match the doc

### ISSUE THREAD

**Issue by Duan-JM** [huan/tensorflow-handbook-tpu#2]
Maybe there is a little typo in the online doc, I think `cluster_resolver` is the right version. 
I have tested it by `TensorFlow 1.15`, so for `cluster_resolver` is good to go for me.

```python
# In online doc https://tf.wiki/zh/appendix/tpu.html
resolver = tf.distribute.resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])

# On Colab TPU Example
resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu='grpc://' + os.environ['COLAB_TPU_ADDR'])
```

**Comment by huan** [comment]
We are targeting the TF2.0 or above.

Cloud you please confirm this case is the same for the TF2.0?

**Comment by Duan-JM** [comment]
Sorry for unclear expression, I have tested on both tf2.0 and tf1.0. The online TPU Colab example using `tf.distribute.cluster_resolver`, however `tf.distribute.resolver` in the doc.

I tested it by using `%tensorflow_version 2.x`to switch between tf2.0 and tf1.15, and my Colab can be found [here](https://colab.research.google.com/drive/1JHKbUIct3NodpyfqdtZamXzdIFrD3L8U)

**Comment by huan** [comment]
Close this issue because TPU works like a charm on Colab now!
